<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-N6FLCJE" failures="1" tests="1" name="AddUser" time="32.809" errors="0" timestamp="2021-12-03T23:55:22 EST">
  <testcase classname="com.teladoc.challenge.testScripts.AddUserTest" name="verifyAddUser" time="16.256">
    <failure type="java.lang.AssertionError" message="User Not Added expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: User Not Added expected [1] but found [0]
at com.teladoc.challenge.testScripts.AddUserTest.verifyAddUser(AddUserTest.java:85)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- verifyAddUser -->
</testsuite> <!-- AddUser -->
