<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-N6FLCJE" failures="1" tests="1" name="DeleteUser" time="17.613" errors="0" timestamp="2021-12-03T23:55:39 EST">
  <testcase classname="com.teladoc.challenge.testScripts.DeleteUserTest" name="deleteUser" time="2.464">
    <failure type="java.lang.AssertionError" message="User Not Deleted expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: User Not Deleted expected [0] but found [1]
at com.teladoc.challenge.testScripts.DeleteUserTest.deleteUser(DeleteUserTest.java:67)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- deleteUser -->
</testsuite> <!-- DeleteUser -->
